### PR TITLE
integration tests for /api/studyplans + configure pipeline to run during pr

### LINKED ISSUE #13: Unit + Integration tests for /api/study_plans
## Story
We must ensure that the features we develop only behave what it is supposed to, and nothing else. This task implements unit and integration tests for the endpoint `/api/study_plans` and serve as a template for future tasks relating to software testing.

Later on, the platform team will configure our CI pipeline to run all tests during Pull Request to ensure that the new changes to do not break any existing code

### PR DESCRIPTION
**Pull request by chinathaip**
This PR:
- implements integration tests for /api/study_plans endpoint - this will serve as a template for future tasks relating to API testing
- configure CI Pipeline to run tests during pull requests

closes https://github.com/stamford-syntax-club/stamfordcenter-backend/issues/13

### CODE REVIEW

**Review by Lxkas — APPROVED** [review]

**Comment by Lxkas** [comment]
FFTM

**Comment by chinathaip** [comment]
> FFTM

What does this mean XD? @Lxkas 

Feel Fine To Me

OR

First Failure To Merge

**Comment by Lxkas** [comment]
> > FFTM
> 
> 
> 
> What does this mean XD? @Lxkas 
> 
> 
> 
> Feel Fine To Me
> 
> 
> 
> OR
> 
> 
> 
> First Failure To Merge

Feel free to merge @chinathaip XD

**Comment by chinathaip** [comment]
> > > FFTM
> > 
> > 
> > What does this mean XD? @Lxkas
> > Feel Fine To Me
> > OR
> > First Failure To Merge
> 
> Feel free to merge @chinathaip XD

555555555555555555555555555555 aight aight

**Pull request merged**
